### PR TITLE
LPS-79141 Shouldn't (or Could) we force DLLinks start by "/documents/"? If the link is absolute is not necessary to check it because the first clause is true.

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Hi @IstvanD 

I've check that the original regexp matches:

```
/documents/12345/0/test.txt/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx
and 
http://localhost:8080/documents/12345/0/test.txt/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx
```

The second one is not necessary since it's an absolute link and the first clause is true, so it should work in current master.

Couldn't we restrict the regepx in order to detect only the current DLLinks?? I think my latest commit does it, but I didn't had time to test it. 

Could you please check it and assert it's right? If not, please fix it and resend to @sergiogonzalez (I'll be out of the office from the next week and thursday and friday spanish office is closed and we do not work)

Thanks for your help, really appreciate it.

**Comment by robertoDiaz** [comment]
/cc @sergiogonzalez

Hi @IstvanD 

I've been talking with @sergiogonzalez about this issue and he suggest another approach to fix this.

Basically is modify the logic that returns the relative link and return it as absolute for this case or modify the relative link and add  convert it in absolute.

I need to check the logic in order to help you perform this changes.

Anyway, since I'm going to be in vacation for some days, and today I do not have bandwith, you could deliver the current solution as SDH to the customer and once I come back I could check it in order to fix it in master. Tell them that this is not the final solution and that it is possible that we change the way it works.

Are you ok with this??

**Comment by IstvanD** [comment]
Hi @robertoDiaz 

Thanks for the help and suggestions, I'll implements the changes probably tomorrow.

I'm wishing you a pleasant holiday!

Bests,
István

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

I have tested your changes, and they are working.
As per your request, I'm sending the pull to @sergiogonzalez
https://github.com/sergiogonzalez/liferay-portal/pull/4294

Best regards,
István

**Pull request closed without merging**
