### PR TITLE
LPS-75749 Do not interpret the entry twice

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
hey @IstvanD 

Can you test my changes??

If everything works, can you push it to sergio??

Thanks!

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

I found that if we pass `userNotificationFeedEntry` to _notification_action.jsp_ via parameter, instead of calculating it there, the same `userNotificationFeedEntry` will be present for all notifications in the list, instead each notification having it's own.

If there is a single unprocessed entry in the list, it's action menu won't be shown.
But, if there is already an entry accepted/declined, and also an unprocessed one, **both** of them will have it's actions menu rendered.
Only if I delete the processed entry, will the other, unprocessed entry's action menu disappear.

**Comment by robertoDiaz** [comment]
Maybe it is because this setAttribute is not a pure set (could you check if it's adding instead of setting (remove + add))?

Anyway, since the interpret action could be heavy, it's better not to repeat it, so could you check the options we have to avoid call this action twice??

Thanks!!

**Comment by IstvanD** [comment]
I think I know the reason.
In _user_notification_entry.jspf_ each `liferay-ui:search-container-column` element gets rendered in their own loop.
For example, there are two entries, `entry1` and `entry2`, and two `liferay-ui:search-container-column` elements in the jps, `liferay-ui:search-container-column-a` and `liferay-ui:search-container-column-b`

When the jsp is rendered, it first renders `liferay-ui:search-container-column-a` for `entry1` and `entry2`, and then renders `liferay-ui:search-container-column-b` for `entry1` and `entry2`

If we set a request param in `liferay-ui:search-container-column-a`, it gets set for `entry1` and then for `entry2`
We want to read the request param in `liferay-ui:search-container-column-b`, but the first value we get is the param set when `entry2` was rendered, because that's let last value that was set.
So we get the param for `entry2` in both `liferay-ui:search-container-column-b#entry1` and `liferay-ui:search-container-column-b#entry2`!

Why this happens the way it does is because of the behavior if the liferay-ui:search-container.
I reckon that we first need to calculate `userNotificationFeedEntry` for every iteration, and then set this value to that it is visible in every `search-container-column`.

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

I added the `userNotificationFeedEntry` as a `rowData`. This solves the issue.

**Pull request closed without merging**
