### PR TITLE
LPS-86181 SF- We don't need to handle this error if we use the right method

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test-sf

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
Just started reviewing.

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

Thank you, the fix works with your modification.

Should I forward it?

Regards,
István

**Comment by IstvanD** [comment]
Sure.
Forwarded to https://github.com/adolfopa/liferay-portal/pull/717

**Pull request closed without merging**
