### PR TITLE
LPS-110189 AutoSF

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Hey Istvan, it looks good to me, anyway, I've fixup some commits to avoid noise.

Can you check if I broke anything

If not, please send it to @adolfopa

**Comment by IstvanD** [comment]
Hi Roberto, it is working fine for me.

I occasionally get the exception

```
2020-03-26 17:53:57.608 ERROR [liferay/mail-2][MailEngine:74] Unable to send message: 432 4.3.2 STOREDRV.ClientSubmit; sender thread limit exceeded [Hostname=VI1PR04MB4463.eurprd04.prod.outlook.com]_ [Sanitized]
com.sun.mail.smtp.SMTPSendFailedException: 432 4.3.2 STOREDRV.ClientSubmit; sender thread limit exceeded [Hostname=VI1PR04MB4463.eurprd04.prod.outlook.com]_ [Sanitized]
```

because Office 365 has a limit for simultaneous connections
https://stackoverflow.com/questions/56088272/432-4-3-2-storedrv-clientsubmit-sender-thread-limit-exceeded
https://docs.microsoft.com/en-us/exchange/troubleshoot/send-emails/smtp-submission-improvements

Should we address this issue in this LPS?

Thank you and best regards,
István

**Comment by robertoDiaz** [comment]
Yes, we could study the case.
Thanks!!

**Comment by IstvanD** [comment]
Hi @robertoDiaz 

@holatuwol suggested configuring the **liferay/mail** parallel destination to have just 1 thread (via `workersCoreSize` and `workersMaxSize` non-constructor args in mail-spring.xml), which will limit the number of simultaneous connections to Office 365. 
This solved the issue.

**Pull request closed without merging**
