### PR TITLE
LPS-98654 Autoconfigure when autocreate

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Hi @IstvanD 

Are you able to test my changes?? They are related with the upgrade we mentioned in the PTR

I think that we also need to create a system configuration for the other case (The PropsKeys.DL_FILE_ENTRY_PREVIEW_DOCUMENT)

Can you check its uses and create the new system conf if needed? 

Thanks!

**Comment by IstvanD** [comment]
Just started reviewing.

**Comment by IstvanD** [comment]
Hi @robertoDiaz 

According to my test results, if I set these in portal-setup-wizard.properties

```
dl.file.entry.thumbnail.custom1.max.height=500
dl.file.entry.thumbnail.custom1.max.width=500
dl.file.entry.thumbnail.custom2.max.height=800
dl.file.entry.thumbnail.custom2.max.width=800
```
and run an upgrade **before** applying 87ecb6f0b0c4f7f578007cc398f3631b025402ec, the upgrade process creates two extra thumbnail AM resolution configurations, **Thumbnail-500x500** and **Thumbnail-800x800**
But after applying 87ecb6f0b0c4f7f578007cc398f3631b025402ec on a same configuration, the resolution configurations are not created.

Is the purpose of 87ecb6f0b0c4f7f578007cc398f3631b025402ec to autoconfigure AMThumbnailConfiguration with the thumbnail AM configurations created by AMCompanyThumbnailConfigurationInitializer?

Thank you and best regards,
István

**Comment by robertoDiaz** [comment]
Yes, that's the idea. 

It was based in other upgrade processes, but I wasn't able to test it.

Maybe a dependency is preventing from that? Can you check it?

If not, tell me, and I'll check it as soon as I can.

Thanks!

**Comment by IstvanD** [comment]
Hi @robertoDiaz 

I made some corrections, and now the AM thumbnail resolutions are created again.
https://github.com/IstvanD/liferay-portal/commit/c78bf9076b2e3e95ac3f1684beb1bb802b535376

**Comment by robertoDiaz** [comment]
Awesome!

Please send it to me, and I'll push it to PT

(if you wish you could provide an SDH based in this)

**Comment by IstvanD** [comment]
Hi @robertoDiaz 

The AMThumbnailConfiguration still needs to be autoconfigured, I'll look into this.

Best regards,
István

**Pull request closed without merging**
