### PR TITLE
LPS-115061 Inverting the isEmpty condition

### PR DESCRIPTION
**Pull request by MarcellGyopos**
Hello @IstvanD ,
Could you please review this pull request?
Thank you and best regards,
Marci

### CODE REVIEW

**Comment by MarcellGyopos** [comment]
ci:test:sf

**Comment by MarcellGyopos** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
ci:test:sf

**Comment by MarcellGyopos** [comment]
I will update the tests

**Pull request closed without merging**
