### PR TITLE
LPS-98654

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @IstvanD

Can you check that this is functionally equivalent to your original fix?  The
main change is that the default values for the configurations are now empty.
Adaptive Media was supposed to replace all those properties, letting the browser
select the best image for each case, so having default values goes against that
idea.

We'll let AM do its thing unless the user explicitly disables it for thumbnails
and/or previews by setting the configuration manually.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
Just started reviewing.

**Comment by IstvanD** [comment]
Hi @adolfopa 

If I open the Adaptive Media page or I want to view an image in Documents and Media,
I get only the following string displayed:

`${processor.processMax()}`

and in the console, the following error message appears

```
2019-08-23 13:01:34.462 ERROR [liferay/monitoring-1][ParallelDestination:55] Unable to process message {destinationName=liferay/monitoring, response=null, responseDestinationName=null, responseId=null, payload=[{displayName=Documents and Media Admin, 
...
com.liferay.portal.kernel.messaging.MessageListenerException: java.lang.NullPointerException
```
I don't know they they are related to the changes made, but nonetheless, I'm unable to test them because of these errors.

Best regards,
István

**Comment by adolfopa** [comment]
I'll look into the error and send you a followup pull request later today.

**Comment by adolfopa** [comment]
@IstvanD Everything works fine on top of today's master.  I'll resend you the same code again; if you get the same error send me a message with the full stack trace.

**Comment by adolfopa** [comment]
See https://github.com/IstvanD/liferay-portal/pull/91

**Pull request closed without merging**
