### PR TITLE
LPS-76191 Made the check for Discussions

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Hey @IstvanD, 

Could you test the pr??

I didn't have enough bandwith to check it, so please, check it carefully. 

We have a ton of test related with this, so you could use them (*UserNotification*Test and *Subscription*Test classes)

Thanks!!

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

The integration tests in the CommentUserNotificationTest and CommentsSubscriptionTest classes will fail of the email notifications are disabled, since the assertions expect 1 item in the inbox, but they receive 0.

Should we adapt the test cases for this scenario? The email notifications are enabled by default.

Thanks!
István

**Comment by robertoDiaz** [comment]
Yes that could be great.

We should create a new test that changes this property value (maybe with a mock is enough or just changing the configuration in persistence -remember to set it back to the original value) that asserts that no email is sent in this case.

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

OK, I'll add this to the test.

Is there an example elsewhere in the codebase where we set property values for the different cases?
As this is an integration test, it starts a server with properties read from portal-ext.properties and runs the test cases on it.
I try to find a way to set the property value from `false `to `true` and vice versa on the fly.
Can this be done with mocking?

Thank you very much,
István

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

I have found that the same tests fail prior to the when `discussion.email.comments.added.enabled=false`

Now I see that these cases were already covered by `testAddUserNotificationWhenEmailNotificationsDisabled()` and `testUpdateUserNotificationWhenEmailNotificationsDisabled()`

**Pull request closed without merging**
