### PR TITLE
[TS] LPS-86807 Wiki attachment image with an ampersand in the file name does not appear

### PR DESCRIPTION
**Pull request by amadeafejes**
Hi István,

Could you please review this pull request?

LPS: https://issues.liferay.com/browse/LPS-86807

Thanks,
Amadea

### CODE REVIEW

**Comment by amadeafejes** [comment]
ci:test:sf

**Comment by amadeafejes** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
Just started reviewing.

**Comment by IstvanD** [comment]
Looks good.
Thanks!

**Comment by IstvanD** [comment]
Forwarded to https://github.com/robertoDiaz/liferay-portal/pull/747

**Pull request closed without merging**
