### PR TITLE
LPS-125750 Upgrade LayoutTable classNameId to 0 from null

### PR DESCRIPTION
**Pull request by MarcellGyopos**
Hi IstvanD,
I fixed the statement.
Could you please review this pull request?
Thank you and best regards,
Marci

### CODE REVIEW

**Comment by MarcellGyopos** [comment]
ci:test:sf

**Comment by MarcellGyopos** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
Just started reviewing.

**Comment by IstvanD** [comment]
Forwarded to https://github.com/liferay-echo/liferay-portal/pull/3619

**Pull request closed without merging**
