### PR TITLE
LPS-125733 Allow pass the sidenavId to the taglib

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Hi @IstvanD 

In the second commit I've add some tips to fix the errors I've discover when multiple info panels are rendered.

Please recheck it and assert that there aren't more cases.

You also ohave t ocheck the browser console:

There some of the warnings i've seen:

```
dl##_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_infoPanelId41525:1 [DOM] Found 2 elements with non-unique id #_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_cmd: (More info: https://goo.gl/9p2vKq) <input class=​"field form-control" id=​"_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_cmd" name=​"_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_cmd" type=​"hidden" value>​ <input class=​"field form-control" id=​"_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_cmd" name=​"_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_cmd" type=​"hidden" value>​
dl##_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_infoPanelId41525:1 [DOM] Found 2 elements with non-unique id #_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_fileEntryId: (More info: https://goo.gl/9p2vKq) <input class=​"field form-control" id=​"_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_fileEntryId" name=​"_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_fileEntryId" type=​"hidden" value=​"41537">​ <input class=​"field form-control" id=​"_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_fileEntryId" name=​"_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_fileEntryId" type=​"hidden" value=​"41525">​
dl##_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_infoPanelId41525:1 [DOM] Found 2 elements with non-unique id #_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_fm: (More info: https://goo.gl/9p2vKq) <form action=​"http:​/​/​localhost:​8080/​web/​guest/​dl?p_p_id=com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx&p_p_lifecycle=1&p_p_state=normal&p_p_mode=view&_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_javax.portlet.action=%2Fdocument_library%2Fedit_file_entry&p_auth=JRiUEpi4" class=​"form  " data-fm-namespace=​"_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_" id=​"_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_fm" method=​"post" name=​"_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_fm">​…​</form>​ <form action=​"http:​/​/​localhost:​8080/​web/​guest/​dl?p_p_id=com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx&p_p_lifecycle=1&p_p_state=normal&p_p_mode=view&_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_javax.portlet.action=%2Fdocument_library%2Fedit_file_entry&p_auth=JRiUEpi4" class=​"form  " data-fm-namespace=​"_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_" id=​"_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_fm" method=​"post" name=​"_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_fm">​…​</form>​
dl##_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_infoPanelId41525:1 [DOM] Found 2 elements with non-unique id #_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_formDate: (More info: https://goo.gl/9p2vKq) <input class=​"field form-control" id=​"_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_formDate" name=​"_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_formDate" type=​"hidden" value=​"1610546313480">​ <input class=​"field form-control" id=​"_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_formDate" name=​"_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_formDate" type=​"hidden" value=​"1610546313544">​
dl##_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_infoPanelId41525:1 [DOM] Found 2 elements with non-unique id #_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_newFolderId: (More info: https://goo.gl/9p2vKq) <input class=​"field form-control" id=​"_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_newFolderId" name=​"_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_newFolderId" type=​"hidden" value>​ <input class=​"field form-control" id=​"_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_newFolderId" name=​"_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_newFolderId" type=​"hidden" value>​
dl##_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_infoPanelId41525:1 [DOM] Found 2 elements with non-unique id #_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_redirect: (More info: https://goo.gl/9p2vKq) <input class=​"field form-control" id=​"_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_redirect" name=​"_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_redirect" type=​"hidden" value=​"http:​/​/​localhost:​8080/​web/​guest/​dl?p_p_id=com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view">​ <input class=​"field form-control" id=​"_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_redirect" name=​"_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_redirect" type=​"hidden" value=​"http:​/​/​localhost:​8080/​web/​guest/​dl?p_p_id=com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view">​
dl##_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_infoPanelId41525:1 [DOM] Found 2 elements with non-unique id #_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_rowIdsDLFileShortcut: (More info: https://goo.gl/9p2vKq) <input class=​"field form-control" id=​"_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_rowIdsDLFileShortcut" name=​"_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_rowIdsDLFileShortcut" type=​"hidden" value>​ <input class=​"field form-control" id=​"_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_rowIdsDLFileShortcut" name=​"_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_rowIdsDLFileShortcut" type=​"hidden" value>​
dl##_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_infoPanelId41525:1 [DOM] Found 2 elements with non-unique id #_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_rowIdsFileEntry: (More info: https://goo.gl/9p2vKq) <input class=​"field form-control" id=​"_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_rowIdsFileEntry" name=​"_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_rowIdsFileEntry" type=​"hidden" value>​ <input class=​"field form-control" id=​"_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_rowIdsFileEntry" name=​"_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_rowIdsFileEntry" type=​"hidden" value>​
dl##_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_infoPanelId41525:1 [DOM] Found 2 elements with non-unique id #_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_rowIdsFolder: (More info: https://goo.gl/9p2vKq) <input class=​"field form-control" id=​"_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_rowIdsFolder" name=​"_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_rowIdsFolder" type=​"hidden" value>​ <input class=​"field form-control" id=​"_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_rowIdsFolder" name=​"_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_rowIdsFolder" type=​"hidden" value>​
dl##_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_infoPanelId41525:1 [DOM] Found 2 elements with non-unique id #_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_urlInput: (More info: https://goo.gl/9p2vKq) <input class=​"form-control" id=​"_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_urlInput" value=​"http:​/​/​localhost:​8080/​documents/​20123/​0/​Captura+de+pantalla+2021-01-07+a+las+15.47.06.png/​5316470f-9eb5-6d6c-c55f-cfce2c52f32a?t=1610455043165">​ <input class=​"form-control" id=​"_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_DfNYkWnweNQx_urlInput" value=​"http:​/​/​localhost:​8080/​documents/​20123/​0/​Captura+de+pantalla+2021-01-08+a+las+13.01.13.png/​28ff4863-57ba-5b63-8b3d-10bafa29f0cf?t=1610455037981">​
```
I think that if we add a randomnamespace for each info panel we could fix it.

I you need some help, ask me in slack.

**Comment by IstvanD** [comment]
Just started reviewing.

**Comment by IstvanD** [comment]
Hi @robertoDiaz 

The browser console warnings appear without your changes as well, so they are not caused by them.

I'm now testing your solution for the cases you suggested.

Best regards,
István

**Comment by IstvanD** [comment]
Hi @robertoDiaz 

I have tested the solution, but haven't found any regressions.

Please let me know if the review can proceed. 

Thank you and best regards,
István

**Pull request closed without merging**
