### PR TITLE
LPS-75064 Reuse

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
Hey @IstvanD there are some tests failing in https://github.com/brianchandotcom/liferay-portal/pull/52565#issuecomment-341147299
Can you please review them and resend?
Thanks!

**Comment by IstvanD** [comment]
Hey @sergiogonzalez 

I ran the tests previously, and I found that they fail because when using `FileUtil.getExtension()` when determining the file extension, I get a `NullPointerException` on the `_file` object in `FileUtil.java`. because it won't be initialized when running the tests, (it doesn't requires the portal to start, thus wiring the objects with Spring).
That is why I created and using the `getFileNameExtension(String fileName)` method.

Best regards,
István

**Comment by sergiogonzalez** [comment]
Hey @IstvanD 
If that's the case, can we set it in the test. We do that in many other places. Please see https://github.com/liferay/liferay-portal/blob/3fd779751810d32fe1ff0171936fc89e0b20db54/modules/apps/knowledge-base/knowledge-base-service/src/test/java/com/liferay/knowledge/base/internal/importer/util/KBArticleMarkdownConverterTest.java#L45 as an example.
Thanks!

**Comment by IstvanD** [comment]
Hey @sergiogonzalez 

I have added the initialization to the setUp, and the tests are passing.
Thank you for the help.

https://github.com/sergiogonzalez/liferay-portal/pull/4094

**Pull request closed without merging**
