### PR TITLE
LPS-70045 Semver

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Hey @IstvanD 

Could yo check if my changes fix the behaviour you are trying to fix??

If you don't understand any of this changes, please tell me and I'll explain :)

Thanks!!!

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

I tested your version and it works great!
I could understand the changes.

Should I resend the pull to you, or send it to Sergio?

Thanks,
István

**Comment by robertoDiaz** [comment]
Send it to me and I'll move it forward to the product team.

Thanks!!

**Comment by IstvanD** [comment]
OK, thanks.

**Comment by IstvanD** [comment]
Pull sent to you https://github.com/robertoDiaz/liferay-portal/pull/539

**Pull request closed without merging**
