### PR TITLE
LPS-112981 Remove p_auth from the query string and send via form data

### PR DESCRIPTION
**Pull request by rgusztus**
Hello @IstvanD ,

Could you please review this pull request?
In case you think its fine please forward it to @antonio-ortega as I'm not a frontend guru unfortunately :)

Thank you!

fyi @istvansajtos, @lipusz

Best Regards,
Robert

### CODE REVIEW

**Comment by antonio-ortega** [comment]
Hi guys,

As I've been mentioned, I'd like to clarify in case you want to forward this pull request to some SME, it should be to WEM SME since the changes are within layout-admin-web.

There is a common misconception about this topic, because it is considered that any frontend issue is going though me, but I am just Frontend Infrastructure SME. Apart from that in every Liferay area (WEM, Collaboration, Forms...) there is some backend side and some frontend side and the SME of each area is taking care of their frontend and backend.

Thanks.

Regards.

**Comment by IstvanD** [comment]
ci:test:sf

**Comment by IstvanD** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
Just started reviewing.

**Comment by IstvanD** [comment]
Forwarded to https://github.com/ealonso/liferay-portal/pull/2947

**Pull request closed without merging**
