### PR TITLE
LPS-71311 Move logic to the lower layers

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Hey @IstvanD 

I've move the logic to a lower level layer, Could you check if it works as expected?

I think this is better because there are more methods named as "updateFileEntryAndCheckIn" and it seems logic that all of them should do this. (Anyway, update the fileEntry with 'fresh' data will not hurt, even for more cases)

If you find any problem, please tell me. Thanks!!

Thanks!!!

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

I'm afraid we can't omit this code https://github.com/IstvanD/liferay-portal/pull/33/commits/8603c896c189801d3ee5f7d691a07569f595a305#diff-1e6a79c4b4cdd1898d0183cb95a01eeeR2651

The call chain goes like this: 

`DLAppServiceImpl.updateFileEntryAndCheckIn() -> DLAppHelperLocalService.updateFileEntry() ->DLAppHelperLocalServiceImpl.updateAsset() -> AssetEntryLocalService.updateEntry()`

In `AssetEntryLocalService.updateEntry()`, the asset entry's `modifiedDate` will be set to the fileEntry's `modifiedDate`.
In order to solve the issue, we have to keep the file entry's and asset entry's modified date in sync.

**Comment by robertoDiaz** [comment]
Mmmmm,

I see, I think that it is failing because we have a leak. The persisted FileEntry is ok, but the reference we have in the DLApp method is outdated. (we could easily assert it checking the modified date from the database)

I think that update the fileEntry (changing repository.checkInFileEntry notation to return it )could make the trick.

Could you check it? Thanks!!

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

You mean, changing the repository.checkInFileEntry() method to return the fileEntry?
Currently, this method is of type void, so I would have to introduce a new, FileEntry returning checkInFileEntry() method in the Repository interface.

Am I understanding this correctly, or am I missing something?

Thank you,
István

**Comment by robertoDiaz** [comment]
Yes, thats the idea, return the modified element so we could "refresh" the fileEntry instance in DLApp and avoid the leak.

**Comment by IstvanD** [comment]
The Liferay(Local)Repository classes' checkInFileEntry() method calls upon dlFileEntry(Local)Service.checkInFileEntry().

```
	@Override
	public void checkInFileEntry(
			long userId, long fileEntryId, String lockUuid,
			ServiceContext serviceContext)
		throws PortalException {

		dlFileEntryLocalService.checkInFileEntry(
			userId, fileEntryId, lockUuid, serviceContext);
	}
```

Therefore, the return type of checkInFileEntry in the DLFileEntryService interface and all of its implementor classes' have to be changed also, as well the logic in DLFileEntryLocalServiceImpl.checkInFileEntry().

The classes that implement DocumentRepository's checkInFileEntry()

image

Should be stick to that approach?

Thank you!

Best regards,
István

**Comment by robertoDiaz** [comment]
Yes, that's the idea.

Anyway, since seems to be a lot of changes, let me agreed it with Collab team in order to avoid doing a lot of work that could be rejected.

I'll tell you  during the day.

I'f you need to provide a fix for the customer, create a new hotfix with the original logic to avoid lock this issue during the review. Are you ok with this?

Thanks!

**Comment by IstvanD** [comment]
Yes, I am also concerned that such numerous API breaking changes could be rejected, not to mention that it would most likely be rejected when I would submit it to backport.

I already supplied a solution to the customer with my original approach, on 6.2.

Thank you, I'm looking forward to the Collab team's response.

**Comment by robertoDiaz** [comment]
I've agreed with @adolfopa that is a good approach. So we could go on with this.

another option is to use the same approach as used in other clients of "repository.checkInFileEntry" that update the reference this way:

`
FileEntry fileEntry = getFileEntry(fileEntryId);
`

**Comment by IstvanD** [comment]
You mean, we could go in DLAppServiceImpl.updateFileEntryAndCheckIn() like this?

```
		fileEntry = getFileEntry(fileEntryId);

		FileVersion latestFileVersion = fileEntry.getLatestFileVersion();

		fileEntry.setModifiedDate(latestFileVersion.getModifiedDate());

		dlAppHelperLocalService.updateFileEntry(
			getUserId(), fileEntry, null, fileEntry.getFileVersion(),
			serviceContext);

		return fileEntry;
```

**Comment by robertoDiaz** [comment]
See https://github.com/IstvanD/liferay-portal/pull/34

I haven't test it, but should work - hopefuly

**Pull request closed without merging**
