### PR TITLE
LPS-110937 Exclude any system layout entry from the sitemap index

### PR DESCRIPTION
**Pull request by dacousalr**
Hi @IstvanD, I have adjusted the query to only return the non-drafts and made the filters stricter to prevent the system layouts from being processed except for the display pages. If you do not see any objections after your review, please, send it to @jkappler. Thanks

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
Just started reviewing.

**Comment by IstvanD** [comment]
Hi @dacousalr 

I have checked the changes. They are working fine, except that 440d4fa80d6cdb0d157b91deb3e1d1390b512554 re-introduces [LPS-108211](https://issues.liferay.com/browse/LPS-108211).

Display Page Templates are System Layouts regardless they are published or not.

**Comment by dacousalr** [comment]
Yes, you are right @IstvanD 

I have fixed the condition to avoid this situation pushing an extra commit.

**Comment by IstvanD** [comment]
Many thanks, @dacousalr !
It is now working as expected.

**Comment by dacousalr** [comment]
Ok @IstvanD ,

When you finished the review, feel free to send it to @jkappler. Thanks

**Comment by IstvanD** [comment]
Thank you.
Forwarded to https://github.com/jkappler/liferay-portal/pull/770

**Pull request closed without merging**
