### PR TITLE
LPS-80082 All the wiki pages of the same Resource have the same createDate. So for each version the modified date is the actual create date. We should change the method in order to return the latest wWikiPages instead of the latest version of the latest WikiPageResources.

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Hey @IstvanD 

Your pull is fine, but I think that I catch and inconsistence in the use of the model.  If you create a new page and modify it twice, all the versions will have the same creation date but different modifiedDate. so the modified date is the "createDate" of each version. Since we want to show the recent changes I think we should return the wiki pages we modified the last week (not the ones whose first version was created the last week). Does it make sense to you??

Can you test if my changes work as expected?

Can you also create some test?? If you are out of time, close the pull and i'll add a few.

If not resend the pull to me with this test and I'll pass it to sergio ASAP

Thanks!!

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

I was wondering if you could find the time to read my last comment.

Thank you!

Best regards,
István

**Comment by robertoDiaz** [comment]
For example:

1. add 2 pages, one of them with more than week, and check that the only the other one is returned.
2. add 2 pages, one with more than a week, update it and check that both are returned
3. check the order

All the similar cases that you could provide :)

Please send it back to me and I'll try to provide more tests if I could. 

Thanks!!

**Comment by IstvanD** [comment]
Hi @robertoDiaz 

Thank you for your answer.

Is there an example for each of these tasks? Eg. in tests for other asset types?

Thank you!

Best regards,
István

**Comment by robertoDiaz** [comment]
Hi,

See:

```
                ServiceContext serviceContext = ServiceContextThreadLocal.getServiceContext();

		Date now = new Date();

		if (isNew && (wikiPage.getCreateDate() == null)) {
			if (serviceContext == null) {
				wikiPage.setCreateDate(now);
			}
			else {
				wikiPage.setCreateDate(serviceContext.getCreateDate(now));
			}
		}

		if (!wikiPageModelImpl.hasSetModifiedDate()) {
			if (serviceContext == null) {
				wikiPage.setModifiedDate(now);
			}
			else {
				wikiPage.setModifiedDate(serviceContext.getModifiedDate(now));
			}
		}

```
It seems that you could pass the create and modified date using the serviceContext, so add and update method could provide the one you prefer. Just pass "now - 2 weeks" to the persistence layer and you could do the tests.

I think this should work.

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

I added the tests, and sent them in pr: https://github.com/robertoDiaz/liferay-portal/pull/673

**Pull request closed without merging**
