### PR TITLE
LPS-75491 Why don't we use the private layout url when the portal requires https?

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Hey @IstvanD 

I've been out of the office for a week.

Can you check my changes?? Do they make sense to you?

Thanks!!

**Comment by IstvanD** [comment]
just started reviewing

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

I have tested you changes, and they are justifiable.

Should I forward it to @sergiogonzalez ?

Thanks,
István

**Comment by robertoDiaz** [comment]
Yes, please.

**Comment by IstvanD** [comment]
Forwarded to https://github.com/sergiogonzalez/liferay-portal/pull/4196

**Pull request closed without merging**
