### PR TITLE
LPS-76164 Control the asset publisher asset category exception when there must be at least one category

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
@IstvanD 

Can you check my changes??

Thanks!!

**Comment by robertoDiaz** [comment]
Hey @IstvanD 

I'm going to close this pr since it seems that there are concerns related with it.

In the original SME I was told that in DL, when we have a required vocabulary, when drag and dropping an element it worked fine, but we have some doubts about that.

I need to clarify this behaviour by myself and see if we could fix this bug or if should consider this as a  limitation.

I'll be in touch.

**Comment by robertoDiaz** [comment]
Hey @IstvanD 

See my last comment in https://issues.liferay.com/browse/LPP-27931

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

Yes, there is a misunderstanding.

I tested multiple file upload, and there I saw that the required categories are automatically added to the category selector section, when the files to be uploaded are previewed. But this does not mean, that hey are yet added to the document.
They'll be only added, when the documents are actually uploaded.
And if there is a required vocabulary **with no category**, the upload will fail.

Drag'n'drop is indeed another case.

**Comment by robertoDiaz** [comment]
Both cases (D&D and selection) are the same because there is no form to select the categories, so both have the same problem. 

As told in the SME request, a deeper investigation drive us to a different solution.

I'll check the needed changes and create a fix if I have bandwith.

Thanks!

**Pull request closed without merging**
