### PR TITLE
Please, refine your solution on top of it: LPS-56446

### PR DESCRIPTION
**Pull request by lipusz**

### CODE REVIEW

**Comment by IstvanD** [comment]
Hi Tibor,

I incorporated the changes in https://github.com/lipusz/liferay-portal/pull/77

**Comment by lipusz** [comment]
Hi István,

I think, when someone sends you back a pull with additional commits, it's
not elegant to fixup those changes into your original commit before
submitting it again to the reviewer. Especially not when the reviewer asked
you to work on top of his pull.

What do you think?

On Tue, Jun 23, 2015 at 10:15 AM, István András Dézsi <
notifications@github.com> wrote:

> Hi Tibor,
>
> I incorporated the changes in lipusz#77
> <https://github.com/lipusz/liferay-portal/pull/77>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IstvanD/liferay-portal/pull/15#issuecomment-114401436>
> .
>



-- 

*Tibor LIPUSZ*

Senior Software Engineer @ TS
Security SME, Subscription Services & Release, Global


*Liferay Hungary Kft.* | H-1138 Budapest, Madarász Viktor u. 47. a-b.,
Hungary

 *Visit Us: **www.liferay.com <http://www.liferay.com/>**  |  Like Us:
**facebook.com/liferay
<http://facebook.com/liferay>**  |  Follow Us: twitter.com/liferay
<http://twitter.com/liferay>*


* <http://twitter.com/liferay>*

 <http://www.liferay.com>

**Comment by IstvanD** [comment]
Hi Tibor,

I think it's elegant, though not a necessarily correct practice. :laughing: 

Sorry, I've resend the pull.

**Comment by lipusz** [comment]
[?]

On Tue, Jun 23, 2015 at 11:16 AM, István András Dézsi <
notifications@github.com> wrote:

> Hi Tibor,
>
> I think it's elegant, though not a necessarily correct practice. [image:
> :laughing:]
>
> Sorry, I've resend the pull.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IstvanD/liferay-portal/pull/15#issuecomment-114416699>
> .
>



-- 

*Tibor LIPUSZ*

Senior Software Engineer @ TS
Security SME, Subscription Services & Release, Global


*Liferay Hungary Kft.* | H-1138 Budapest, Madarász Viktor u. 47. a-b.,
Hungary

 *Visit Us: **www.liferay.com <http://www.liferay.com/>**  |  Like Us:
**facebook.com/liferay
<http://facebook.com/liferay>**  |  Follow Us: twitter.com/liferay
<http://twitter.com/liferay>*


* <http://twitter.com/liferay>*

 <http://www.liferay.com>

**Comment by IstvanD** [comment]
I mean in a way that the pull consists of fewer commits.

It's a joke, and a bad one, and I did it by mistake.

**Comment by lipusz** [comment]
I got it. Don't worry. ;-]

On Tue, Jun 23, 2015 at 11:21 AM, István András Dézsi <
notifications@github.com> wrote:

> I mean in a way that the pull consists of fewer commits.
>
> It's a joke, and a bad one, and I did it by mistake.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IstvanD/liferay-portal/pull/15#issuecomment-114417353>
> .
>



-- 

*Tibor LIPUSZ*

Senior Software Engineer @ TS
Security SME, Subscription Services & Release, Global


*Liferay Hungary Kft.* | H-1138 Budapest, Madarász Viktor u. 47. a-b.,
Hungary

 *Visit Us: **www.liferay.com <http://www.liferay.com/>**  |  Like Us:
**facebook.com/liferay
<http://facebook.com/liferay>**  |  Follow Us: twitter.com/liferay
<http://twitter.com/liferay>*


* <http://twitter.com/liferay>*

 <http://www.liferay.com>

**Pull request closed without merging**
