### PR TITLE
LPS-110189 SMPT doesn't require the security to be true. Handle this case.

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Hey @IstvanD 

Can you test my changes?

Best regards

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
Just started reviewing.

**Comment by IstvanD** [comment]
I think my change 3befa4c9e8752a159d93f21ba4733c2591872a3b is not necessary, as the user can allow a custom sender email address in Office365.

**Pull request closed without merging**
