### PR TITLE
LPS-93391 Use the Configuration interfaces. Settings pattern is not used anymore.

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Hey @IstvanD 

I've done some changes and assert that the configuration is shown, but I do not have time to check and fix all the cases.

Can you check my changes and fix it where needed?

Thanks!!

**Comment by robertoDiaz** [comment]
Hey @IstvanD 

Any update on this??

Thanks!!

**Comment by IstvanD** [comment]
Hi @robertoDiaz 

I'm currently testing it.
I'll come back to you once I'm finished with it.

Thank you and best regards,
István

**Comment by IstvanD** [comment]
Hi @robertoDiaz 

I add to apply some changed to the solution in order to work and follow existing patterns.

I submitted my modifications in https://github.com/robertoDiaz/liferay-portal/pull/768

Best regards,
István

**Pull request closed without merging**
