### PR TITLE
LPS-77290 Add back-end validation for Wiki page title lentgh

### PR DESCRIPTION
**Pull request by sorin-pop**

### CODE REVIEW

**Comment by sorin-pop** [comment]
ci:test

**Comment by IstvanD** [comment]
ci:retest

**Comment by IstvanD** [comment]
ci:test

**Comment by IstvanD** [comment]
Started reviewing

**Comment by IstvanD** [comment]
Forwarded to https://github.com/robertoDiaz/liferay-portal/pull/637

**Pull request closed without merging**
